services:
  web:
    image: php:8.1-apache
    container_name: php_app_container
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    links:
      - db:db
    entrypoint: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"
    networks:
      - lab_network

  db:
    image: mysql:5.7
    container_name: mysql_db_container
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge
    
volumes:
  mysql_data:
